name: base
dependencies:
  - albumentations
  # - argparse
  - beakerx
  - biopython
  - bokeh
  - botorch
  - boto3
  - bottleneck
  - bqplot
  - captum
  - cffi
  - click
  - click-aliases
  - click-completion
  - click-config-file
  - click-help-colors
  - click-log
  - click-option-group
  - click-params
  - click-plugins
  - click-spinner
  - cling
  - cloudpickle
  - colorcet
  - cppyy
  - cppyy-cling
  - cudatoolkit =10.1.*
  - cupti
  - cupy >=7.6
  - cython
  - dask >=2.19
  - dask-cuda
  - dask-distance
  - dask-funk
  - dask-gateway
  - dask-gateway-server
  - dask-glm
  - dask-image
  - dask-imread
  - dask-jobqueue
  - dask-memusage
  - dask-ml
  - dask-searchcv
  - dask-xgboost
  - datashader
  # - detectron2
  - dill
  - discretize
  - distributed
  - etcd
  - ffmpeg-python
  - findspark
  - firelight
  - google-cloud-storage
  - h5py
  - holoviews
  - hvplot
  - ignite
  - imagecodecs
  - imageio
  - imageio-ffmpeg
  - inferno
  - intake
  - intake-parquet
  - intake-xarray
  - ipython
  - itk >=5
  - itk-meshtopolydata
  - javabridge
  - jsonpatch
  - k3d
  - kaggle
  - lmdb
  - mayavi
  - matplotlib >=3.2
  - matplotlib-scalebar
  - memory_profiler
  - menpo
  - menpo3d
  - menpodetect
  - menpofit
  - mrcfile
  - mypy
  - napari
  - natsort
  - networkx
  - nibabel
  - numba
  - numcodecs
  - numexpr
  - numpy >=1.18
  - opencv >=4.2
  - openpyxl
  - pandas >=1.0.4
  - pandas-datareader
  - pandas_ml
  - pandasql
  - panel
  - pillow
  - pims
  - plotly
  - py4j
  # - py-openimageio
  - pyarrow
  - pybind11
  - pycocotools
  - pydicom
  - pyfftw
  - pynrrd
  - pynvml
  - pyodbc
  - pyopengl
  - pyqt
  - pyqtgraph
  - pyside2
  - pysoundfile
  - pyspark >=3
  # - pyspark-stubs
  - pytables
  - pytesseract
  - python =3.7.*
  - python-confluent-kafka
  - python-dateutil
  - python-language-server
  - pytorch =1.6.*
  - pytorch-lightning
  - pyvista
  - pyviz_comms
  - pywavelets
  # - pyxtensor
  - pyyaml
  - pyzbar
  # - rapids >=0.14
  # - rapids-xgboost
  - recommonmark
  - roifile
  - scikit-bio
  - scikit-build
  - scikit-data
  - scikit-fmm
  - scikit-fuzzy
  - scikit-garden
  - scikit-image >=0.16
  - scikit-learn >=0.23
  - scikit-learn-extra
  - scikit-mdr
  - scikit-multiflow
  - scikit-optimize
  - scikit-plot
  - scikit-surprise
  - scikit-sparse
  - scikit-umfpack
  - scipy >=1.5
  - seaborn
  - sentencepiece
  - simpleitk >=1.2.4
  - skorch
  - slicerator
  - sox
  - sqlalchemy
  - sqlalchemy-utils
  - sqlite
  - statsmodels
  - sympy
  - tabulate
  - tensorboardx
  - tensorflow-gpu =2.2.*
  - tetgen
  - tifffile
  - toml
  - torch-model-archiver
  - torchaudio
  # - torchserve
  - torchtext
  - torchvision
  - tqdm
  - transforms3d
  - umap-learn
  - untangle
  - urllib3
  - visdom
  - vispy
  - vtk
  - xarray >=0.15
  - xarray-extras
  - xarray-spatial
  - xeus-cling
  - xgboost
  - xlrd
  - xlsxwriter
  - xlwt
  - xmltodict
  - xrviz
  - xtensor
  - xtensor-blas
  - xtensor-fftw
  # - xtensor-io
  - xtensor-python
  - yaml
  - z5py
  - zarr
  - zbarlight
# Utilities
  - autopep8
  - black
  - breathe
  - conda-build
  - conda-verify
  - flake8
  - isort =4
  - jedi
  - mccabe
  - papermill
  - pycodestyle
  - pydocstyle
  - pyflakes
  - pylama
  - pylint
  - pyls-black
  - pyls-mypy
  - pytest
  - pytest-flake8
  - pytest-mccabe
  - pytest-mock
  - pytest-mpl
  - pytest-mypy
  - pytest-pylint
  - rope
  - sphinx
  - sphinx-argparse
  - sphinx-autoapi
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-automodapi
  - sphinx-click
  - sphinx-issues
  - sphinx-jinja
  - sphinx-markdown-tables
  - sphinx-math-dollar
  - voila
  - yapf
# Jupyter
  - itkwidgets
  - ipykernel
  - ipywidgets
  # - jupyter_bokeh
  - jupyterlab
  - jupyterlab-git
  - nb_conda_kernels
# Frameworks
  - airflow
  - dagit
  - dagster
  - metaflow
  - mlflow
  - neptune-client
  - neptune-notebooks
# pip
  - pip
  - pip:
    - antspyx
    - arrayfire
    - augment-nd
    - baal
    - elasticdeform
    - faust
    # for FlyWheel sever v14.0.2
    - flywheel-cli ==12.4.*
    - flywheel-sdk ==12.4.*
    - mxnet_cu101mkl
    - numbagg
    - pymeshfix
    - python-bioformats
    - ray
    # - scikit-cuda  # (outdated?)
    - sphinx-rtd-theme
    - tensorlayer[all]
    # - torchelastic
    - git+https://github.com/cocodataset/panopticapi.git
    - git+https://github.com/waspinator/pycococreator.git
    - git+https://github.com/bhoeckendorf/pyklb.git@skbuild
# Utilities
    - exhale
    - pyls-isort
    - pytest-pycodestyle
# Jupyter
    # - dask_labextension
    - jupyter_http_over_ws
    # - jupyter-tensorboard
    # nvdashboard, dash, code-fromatter, tensorboard
    - nbdev
# Frameworks
    - prefect[templates,viz]
    - trains
    - trains-agent
