name: base
dependencies:
  - addict
  - aiofiles
  - aioftp
  - aiohttp
  - aioitertools
  - albumentations
  - av
  - baal
  - beakerx
  - biopython
  - bokeh
  - botorch
  - boto3
  - bottleneck
  - bqplot
  - captum
  - cffi
  - click
  - click-aliases
  - click-completion
  - click-config-file
  - click-help-colors
  - click-log
  - click-option-group
  - click-params
  - click-plugins
  - click-spinner
  - cling
  - cloudpickle
  - colorcet
  - cppyy
  - cppyy-cling
  # - cudatoolkit =10.1.*
  # - cupti
  - cupy
  - cython
  - dask
  - dask-cuda
  - dask-distance
  - dask-funk
  - dask-gateway
  - dask-gateway-server
  - dask-glm
  - dask-image
  - dask-imread
  - dask-jobqueue
  - dask-memusage
  - dask-ml
  - dask-searchcv
  # - dask-xgboost
  - datashader >=0.12
  # - detectron2
  - discretize
  - distributed
  - etcd
  - fbprophet
  - ffmpeg-python
  - firelight
  - fsspec
  - google-cloud-storage
  - gpytorch
  - h5py
  - hdbscan
  - hiplot
  - holoviews
  - hvplot
  - hydra-core
  - ignite
  - imagecodecs
  - imageio
  - imageio-ffmpeg
  - imgaug
  - intake
  # - intake-parquet  # ClobberError
  - intake-xarray
  - ipython
  - itk
  # - itk-meshtopolydata  # no py38
  - k3d
  - kaggle
  - librosa
  - mayavi
  - matplotlib >=3.4
  - matplotlib-scalebar
  - memory_profiler
  - menpo
  - menpo3d
  - menpodetect
  - menpofit
  - mrcfile
  - mypy
  - napari
  - natsort
  - networkx
  - nibabel
  - numba
  - numcodecs
  - numexpr
  - numpy >=1.20
  - opencv
  - openpyxl
  - pandas >=1.2
  - pandas-datareader
  - pandas-gbq
  - panel
  - pillow >=8.2
  - pims
  - plotly
  - py4j
  # - py-openimageio
  - pyarrow
  - pybind11
  - pycocotools
  - pydicom
  - pyfftw
  - pynrrd
  - pynvml
  - pyodbc
  - pyopengl
  - pyqt
  - pyqtchart
  - pyqtgraph
  - pyside2
  - pysoundfile
  - pytables
  - pytesseract
  - python >=3.8
  - python-dateutil
  - python-javabridge
  - python-kaleido
  - python-language-server
  - python-lmdb
  - python-memcached
  - pytorch >=1.7
  - pytorch-lightning
  - pyvista
  - pyviz_comms
  - pywavelets
  - pyxtensor
  - pyyaml
  - pyzbar
  # - qgrid
  # - rapids-blazing >=0.18
  ## - rapids-xgboost
  - recommonmark
  - roifile
  - scikit-bio
  - scikit-build
  - scikit-fmm
  - scikit-fuzzy
  - scikit-image
  - scikit-learn
  - scikit-optimize
  - scikit-surprise
  - scikit-sparse
  - scipy >=1.6
  - seaborn
  - sentencepiece
  - simpleitk >=2
  - skorch
  - slicerator
  - sox
  - spatialpandas
  - sqlalchemy
  - sqlalchemy-utils
  - sqlite
  - statsmodels
  - streamz
  - sympy
  - tabulate
  - tensorboardx
  - tensorflow-gpu >=2.2
  - tetgen
  - tifffile
  - toml
  - torch-model-archiver
  - torchaudio >=0.7
  - torchtext >=0.8
  - torchvision >=0.8
  - tqdm
  - transforms3d
  - umap-learn
  - untangle
  - urllib3
  - visdom
  - vispy
  - vtk
  - xarray >=0.17
  - xarray-spatial
  - xeus-cling
  # - xframe
  - xgboost
  - xlrd
  - xlsxwriter
  - xlwt
  - xmltodict
  - xpublish
  - xrft
  - xrviz
  # - xsimd
  - xtensor
  # - xtensor-blas
  # - xtensor-fftw
  # - xtensor-io
  - xtensor-python
  # - xtensor-sparse
  # - xtensor-zarr
  # - xtl
  - yaml
  - zarr
  - zarray
  - zbarlight
# Utilities
  - autopep8
  - black
  - breathe
  - conda-build
  - conda-verify
  - flake8
  - isort
  - jedi
  - mccabe
  - papermill
  - pycodestyle
  - pydocstyle
  - pyflakes
  - pylama
  - pylint
  - pyls-black
  - pyls-isort
  - pyls-mypy
  - pytest >=6.2
  - pytest-asyncio
  - pytest-flake8
  - pytest-mccabe
  - pytest-mock
  - pytest-mpl
  - pytest-mypy
  - pytest-pycodestyle
  - pytest-pylint
  - recommonmark
  - rope
  - sphinx >=3.5
  - sphinx-argparse
  - sphinx-autoapi
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-automodapi
  - sphinx-click
  - sphinx-issues
  - sphinx-jinja
  - sphinx-markdown-tables
  - sphinx-math-dollar
  - sphinx_rtd_theme
  - typeguard
  - voila
  - yapf
# Jupyter
  - dtale
  - itkwidgets
  - ipykernel
  - ipympl
  - ipyvolume
  - ipywidgets
  # - jupyter_bokeh
  - jupyter_http_over_ws
  - jupyterlab >=3.0.13
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - nb_conda_kernels
  - nbdev
# Frameworks
  - metaflow
  - mlflow
# pip
  - pip
  - pip:
    - aiocache
    - antspyx
    - arrayfire
    - git+https://github.com/stardist/augmend.git
    - augment-nd
    - ax-platform
    - dataget
    - elasticdeform
    # - elegy
    # - fairscale  # pip error
    - faust
    - flywheel-sdk
    - gunpowder
    # - git+https://github.com/deepmind/dm-haiku
    - iterative-stratification
    # - jax
    # - jaxlib ==0.1.57+cuda101
    - lightly
    - ml-collections
    - monai
    # - mpi4jax
    # - neuroglancer
    # - neuroglancer-annotation-ui
    - numbagg
    - ome-zarr
    # - omero-py
    # - omero-rois
    # - pandasgui
    - git+https://github.com/cocodataset/panopticapi.git
    - git+https://github.com/waspinator/pycococreator.git
    - git+https://github.com/bhoeckendorf/pyklb.git@skbuild
    - pymeshfix
    - pyn5
    - python-bioformats
    - ray  # move to conda once that has version >=1.2
    # - river  # pip error
    # - scikit-cuda
    - tensorlayer
    - tensorstore
    - torchelastic
# Utilities
    - exhale
# Jupyter
    # - dask_labextension
    # - jupyter-tensorboard
    # nvdashboard, dash, code-fromatter, tensorboard
# Frameworks
    - clearml
    - clearml-agent
