name: default
channels:
  - pytorch
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - ipython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - pynvml
  - itkwidgets
  - jupyterlab-git
  - jupyterlab_code_formatter
  - pyviz_comms
  - jupyter_bokeh
  - black
  - autopep8
  - isort
  - sphinx
  #- airflow
  - albumentations
  - biopython
  - bokeh
  - boto3
  - bottleneck
  - cffi
  - cling
  - colorcet
  - conda-build
  - cppyy
  - cppyy-cling
  - cudatoolkit=10.1
  - cupti
  - cupy
  - cython
  - dask
  - dask-distance
  - dask-funk
  - dask-gateway
  - dask-gateway-server
  - dask-glm
  - dask-image
  - dask-imread
  - dask-jobqueue
  - dask-memusage
  - dask-ml
  - dask-searchcv
  - dask-xgboost
  - datashader
  - discretize
  - distributed
  - google-cloud-storage
  - h5py
  - holoviews
  - hvplot
  - imageio
  - intake
  - intake-avro
  - intake-parquet
  - intake-sql
  - intake-xarray
  - isort
  - itk
  - javabridge
  - jsonpatch
  - lmdb
  - mayavi
  - matplotlib
  - mccabe
  - memory_profiler
  - menpo
  - menpo3d
  - menpodetect
  - menpofit
  - mlflow
  - mrcfile
  - napari
  - natsort
  - networkx
  - nibabel
  - nteract_on_jupyter
  - nteract-scrapbook
  - numba
  - numcodecs
  - numexpr
  - openpyxl
  - pandas
  - panel
  - pillow
  - pims
  - plotly
  - prefect
  - pycocotools
  - pycodestyle
  - pydicom
  - pydocstyle
  - pyflakes
  - pygments
  - pylint
  - pynvml
  - pyodbc
  - pyopengl
  - pyqt
  - pyqtgraph
  - pyside2
  - pysoundfile
  - pytables
  - pytesseract
  - python-dateutil
  - python-language-server
  - pyvista
  - pywavelets
  - pyyaml
  - pyzbar
  - rapids
  - rope
  - scikit-bio
  - scikit-build
  - scikit-data
  - scikit-fmm
  - scikit-fuzzy
  - scikit-garden
  - scikit-image
  - scikit-learn
  - scikit-learn-extra
  - scikit-mdr
  - scikit-multiflow
  - scikit-optimize
  - scikit-plot
  - scikit-surprise
  - scikit-sparse
  - scikit-umfpack
  - scikit-video
  - scipy
  - seaborn
  - simpleitk
  - slicerator
  - sox
  - sphinx
  - sqlalchemy
  - sqlalchemy-utils
  - sqlite
  - statsmodels
  - sympy
  - tabulate
  - tetgen
  - tifffile
  - tqdm
  - transforms3d
  - umap-learn
  - urllib3
  - vispy
  - xarray
  - xeus-cling
  - xgboost
  - xlrd
  - xlsxwriter
  - xlwt
  - xmltodict
  - xrviz
  - yaml
  - yapf
  - z5py
  - zarr
  - zbarlight
  - pytorch
  - torchvision
  - torchaudio
  - torchtext
  - visdom
  - vtk
  - skorch
  - pip
  - pip:
    - jupyter_http_over_ws
    #- dask_labextension
    #- jupyterlab-nvdashboard
    #- jupyter-tensorboard
    - apache-airflow
    - baal
    - dask-ndfilters
    - dask-ndfourier
    - dask-ndmeasure
    - dask-ndmorph
    - dagit
    - dagster
    - dagster-airflow
    - dagster-bash
    - dagster-cron
    - dagster-dask
    - dagster-pandas
    - dagster-postgres
    - dagster-shell
    - dagster-slack
    - dagster-ssh
    - dagstermill
    - flywheel-cli
    - flywheel-sdk
    - imagecodecs
    - memory-profiler
    - metaflow
    - mxnet-cu101mkl
    - numbagg
    - opencv-contrib-python-headless
    - pyls-isort
    - pyls-cwrap
    - pyls-mypy
    - pyls-black
    - pyls-black-macchiato
    - pymeshfix
    - pynrrd
    - python-bioformats
    - ray
    - sentencepiece
    - untangle
    - tensorflow>=2.2
    - tensorlayer
    - git+https://github.com/cocodataset/panopticapi.git
    - git+https://github.com/waspinator/pycococreator.git
